<?php

namespace Dashed\DashedEcommerceCore\Filament\Resources\CartResource\Pages;

use Filament\Resources\Pages\ViewRecord;
use Dashed\DashedEcommerceCore\Filament\Resources\CartResource;

class ViewCart extends ViewRecord
{
    protected static string $resource = CartResource::class;

    protected function mutateFormDataBeforeFill(array $data): array
    {
        $data['user'] = $this->record->user ? $this->record->user->name : '-';

        return parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }
}
